services:
  - type: web
    name: student-performance
    env: python
    plan: free
    rootDir: mlproject
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
